//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratorData.MyMessage", typeof(MyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Insert Data In Table?.
        /// </summary>
        internal static string ConfirmInsertData {
            get {
                return ResourceManager.GetString("ConfirmInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occured Error When Saving Data..
        /// </summary>
        internal static string ErrorInsertData {
            get {
                return ResourceManager.GetString("ErrorInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Average is Not Within the Correct Range.
        /// </summary>
        internal static string InappropriateRangeAverage {
            get {
                return ResourceManager.GetString("InappropriateRangeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value Cannot Bigger From Maximum Value..
        /// </summary>
        internal static string IncorrectMinOrMax {
            get {
                return ResourceManager.GetString("IncorrectMinOrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Is Empty..
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation Was Successful..
        /// </summary>
        internal static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Correct Information..
        /// </summary>
        internal static string PleaseEnterData {
            get {
                return ResourceManager.GetString("PleaseEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string TitleMessageQuestion {
            get {
                return ResourceManager.GetString("TitleMessageQuestion", resourceCulture);
            }
        }
    }
}
